apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nodejs-deployment
  labels:
    name: nodejs-deployment
spec: 
  replicas: 4 
  selector: 
    matchLabels: 
      app: nodejs 
  template: 
    metadata:
      name: nodejs
      labels: 
        app: nodejs 
    spec: 
      containers: 
      - name: nodejs 
        image: rijalefendi/nodejs-in-kubernetes:1.0
        ports: 
        - containerPort: 3002
